# Generated by Django 5.1.7 on 2025-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user_uuid', models.CharField(max_length=100)),
                ('workflow_name', models.CharField(max_length=100)),
                ('workflow_description', models.TextField(blank=True, null=True)),
                ('workflow_status', models.CharField(default='pending', max_length=100)),
                ('workflow_trigger_time', models.DateTimeField(blank=True, null=True)),
                ('workflow_trigger_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_trigger_frequency_value', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_trigger_frequency_unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
