# Generated by Django 5.1.7 on 2025-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformusers',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
